// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Blame(arg1:string):Promise<string>;

export function BranchRename(arg1:string,arg2:string):Promise<string>;

export function CherryPick(arg1:string):Promise<string>;

export function Clean(arg1:string):Promise<string>;

export function Clone(arg1:string):Promise<string>;

export function Commit(arg1:string,arg2:string):Promise<string>;

export function CreateBranch(arg1:string):Promise<string>;

export function DeleteBranch(arg1:string):Promise<string>;

export function Diff(arg1:string):Promise<string>;

export function Fetch(arg1:string):Promise<string>;

export function GetBranches():Promise<Array<string>>;

export function GetConflicts():Promise<Array<string>>;

export function GetCurrentBranch():Promise<string>;

export function GetRepoPath():Promise<string>;

export function Init():Promise<string>;

export function IsGitAvailable():Promise<boolean>;

export function IsRepoInitialized():Promise<boolean>;

export function Log(arg1:string):Promise<string>;

export function LsFiles(arg1:string):Promise<string>;

export function MagicSync():Promise<string>;

export function Merge(arg1:string):Promise<string>;

export function OpenFolder():Promise<string>;

export function Pull(arg1:string):Promise<string>;

export function Push(arg1:string):Promise<string>;

export function ReadGitIgnore():Promise<string>;

export function Rebase(arg1:string,arg2:string):Promise<string>;

export function Reflog(arg1:string):Promise<string>;

export function Remote(arg1:string,arg2:string):Promise<string>;

export function Reset(arg1:string,arg2:string):Promise<string>;

export function ResolveConflict(arg1:string,arg2:string):Promise<string>;

export function Revert(arg1:string):Promise<string>;

export function RunCommands(arg1:string):Promise<string>;

export function SelectRepo():Promise<string>;

export function Shortlog(arg1:string):Promise<string>;

export function Show(arg1:string,arg2:string):Promise<string>;

export function Stage(arg1:string):Promise<string>;

export function Stash(arg1:string):Promise<string>;

export function Status(arg1:string):Promise<string>;

export function SwitchBranch(arg1:string):Promise<string>;

export function Tag(arg1:string,arg2:string):Promise<string>;

export function UndoLastCommit():Promise<string>;

export function Worktree(arg1:string,arg2:string):Promise<string>;

export function WriteGitIgnore(arg1:string):Promise<void>;
